[package]
org = "nidunidk"
name = "greeter_service"
version = "0.1.0"
distribution = "2201.13.1"

[[dependency]]
org = "ballerina"
name = "grpc"
version = "1.14.4"


[build-options]
observabilityIncluded = true
